version: "3.7"

services:
  auth:
    build: ./auth
    ports:
      - "8081:8081"
    networks:
      - auth-database
      - auth-booking
    depends_on:
      database:
        condition: service_healthy

  booking:
    build: ./booking
    ports:
      - "8082:8082"
    networks:
      - booking-database
      - auth-booking
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    container_name: postgres
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - auth-database
      - booking-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 15s
      timeout: 3s
      interval: 10s
      retries: 12

networks:
  auth-booking:
  auth-database:
  booking-database: