-- liquibase formatted sql
-- changeset dvmukhin@edu.hse.ru:1
create table if not exists "order"
(
    id              integer generated by default as identity primary key,
    user_id         integer not null references "user",
    from_station_id integer not null references station,
    to_station_id   integer not null references station,
    status          integer not null,
    created         timestamp default CURRENT_TIMESTAMP
);
-- rollback delete order;
