-- liquibase formatted sql
-- changeset dvmukhin@edu.hse.ru:1
create table if not exists station
(
    id      integer generated by default as identity primary key,
    station varchar(50) not null
);
-- rollback delete station;

-- changeset dvmukhin@edu.hse.ru:2
insert into station (station) values ('Moscow');
insert into station (station) values ('Saint Petersburg');
insert into station (station) values ('Novosibirsk');
insert into station (station) values ('Yekaterinburg');
insert into station (station) values ('Kazan');
insert into station (station) values ('Nizhny Novgorod');
-- rollback delete from station where station = 'Moscow';
-- rollback delete from station where station = 'Saint Petersburg';
-- rollback delete from station where station = 'Novosibirsk';
-- rollback delete from station where station = 'Yekaterin
-- rollback delete from station where station = 'Kazan';
-- rollback delete from station where station = 'Nizhny Novgorod';
-- rollback delete from station where station = 'Moscow';
