-- liquibase formatted sql
-- changeset dvmukhin@edu.hse.ru:1
create table if not exists "session"
(
    id      integer generated by default as identity primary key,
    user_id integer      not null references "user",
    token   varchar(255) not null,
    expires timestamp    not null
);
-- rollback delete "session";
