-- liquibase formatted sql
-- changeset dvmukhin@edu.hse.ru:1
create table if not exists "user"
(
    id       integer generated by default as identity primary key,
    nickname varchar(50)  not null,
    email    varchar(100) not null unique,
    password varchar(255) not null,
    created  timestamp default CURRENT_TIMESTAMP
);
-- rollback delete user;